services:
  - type: web
    name: youtube-transcript-tool
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    runtime: python
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
